server:
  port: 16114

spring:
  application:
    name: ts-admin-travel-service
  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0
  http:
    multipart:
      maxFileSize: 100Kb
      maxRequestSize: 100Kb

