apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-admin-order-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-admin-order-service
    spec:
      containers:
      - name: ts-admin-order-service
        image: 10.141.211.160:5000/f12/cluster-ts-admin-order-service
        imagePullPolicy: Always
        ports:
        - containerPort: 16112

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-cancel-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-cancel-service
    spec:
      containers:
      - name: ts-cancel-service
        image: 10.141.211.160:5000/f12/cluster-ts-cancel-service
        imagePullPolicy: Always
        ports:
        - containerPort: 18885

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-inside-payment-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-inside-payment-service
    spec:
      containers:
      - name: ts-inside-payment-service
        image: 10.141.211.160:5000/f12/cluster-ts-inside-payment-service
        imagePullPolicy: Always
        ports:
        - containerPort: 18673

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-login-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-login-service
    spec:
      containers:
      - name: ts-login-service
        image: 10.141.211.160:5000/f12/cluster-ts-login-service
        imagePullPolicy: Always
        ports:
        - containerPort: 12342

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-order-other-service
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: ts-order-other-service
    spec:
      containers:
      - name: ts-order-other-service
        image: 10.141.211.160:5000/f12/cluster-ts-order-other-service
        imagePullPolicy: Always
        ports:
        - containerPort: 12032

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-order-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-order-service
    spec:
      containers:
      - name: ts-order-service
        image: 10.141.211.160:5000/f12/cluster-ts-order-service
        imagePullPolicy: Always
        ports:
        - containerPort: 12031

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-sso-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-sso-service
    spec:
      containers:
      - name: ts-sso-service
        image: 10.141.211.160:5000/f12/cluster-ts-sso-service
        imagePullPolicy: Always
        ports:
        - containerPort: 12349

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-station-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-station-service
    spec:
      containers:
      - name: ts-station-service
        image: 10.141.211.160:5000/f12/cluster-ts-station-service
        imagePullPolicy: Always
        ports:
        - containerPort: 12345

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-verification-code-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-verification-code-service
    spec:
      containers:
      - name: ts-verification-code-service
        image: 10.141.211.160:5000/f12/cluster-ts-verification-code-service
        imagePullPolicy: Always
        ports:
        - containerPort: 15678

---

apiVersion: v1
kind: Service
metadata:
  name: ts-admin-order-service
spec:
  ports:
    - name: http
      port: 16112
  selector:
   app: ts-admin-order-service

---
apiVersion: v1
kind: Service
metadata:
  name: ts-cancel-service
spec:
  ports:
    - name: http
      port: 18885
  selector:
   app: ts-cancel-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-inside-payment-service
spec:
  ports:
    - name: http
      port: 18673
  selector:
   app: ts-inside-payment-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-login-service
spec:
  ports:
    - name: http
      port: 12342
  selector:
   app: ts-login-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-order-other-service
spec:
  ports:
    - name: http
      port: 12032
  selector:
   app: ts-order-other-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-order-service
spec:
  ports:
    - name: http
      port: 12031
  selector:
   app: ts-order-service

---
apiVersion: v1
kind: Service
metadata:
  name: ts-sso-service
spec:
  ports:
    - name: http
      port: 12349
  selector:
   app: ts-sso-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-station-service
spec:
  ports:
    - name: http
      port: 12345
  selector:
   app: ts-station-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-verification-code-service
spec:
  ports:
    - name: http
      port: 15678
  selector:
   app: ts-verification-code-service
---
