spring:

  application:
    name: ts-sso-service
  redis:
    host: redis
    port: 6379
  data:
    mongodb:
      host: ts-account-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017

  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0

  

# HTTP Server
server:
  port: 12349  # HTTP (Tomcat) port